env : "local"
storage_path: "./storage/storage.db" #Файл с БД
http_server:
  address: "localhost:8082"
  timeout: 4s #Время на чтение запроса и отправку ответа
  idle_timeout: 30s #Время жизни соединения с клиентом